### PR TITLE
Fix alternatives for *.clj

### PR DESCRIPTION
**Pull request by mluts**
Hi, seems like #15 will hang forever, i'd like to have this sooner

### CODE REVIEW

**Comment by tpope** [comment]
Please indent the `\` in the standard way. Don't break `gg=G`.

**Comment by mluts** [comment]
@tpope done

**Comment by tpope** [comment]
I did not realize `gg=G` was already broken. I'm teasing it apart into 2 separate commits.

**Comment by mluts** [comment]
Did not realize it's already merged, thank you!

**Pull request closed without merging**
